### ISSUE TITLE
Internal snapshot

### ISSUE THREAD

**Issue by phamngocsonls** [nhanhoadocs/thuctapsinh#66]
Hình như với interal snapshot thì khi create-snapshot thì VM bị pause nên cũng không cần pause để không lưu trạng thái RAM.

**Comment by niemdinhtrong** [comment]
> Hình như với interal snapshot thì khi create-snapshot thì VM bị pause nên cũng không cần pause để không lưu trạng thái RAM.

Cảm ơn thông tin của bạn nhé! Để mình sửa lại.
